name: thryve
description: "Track your gym progress"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  http: ^1.3.0
  shared_preferences: ^2.3.5
  email_validator: ^3.0.0
  fluttertoast: ^8.2.10
  ionicons: ^0.2.2
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  # fuzzy: <1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Instrument Sans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
        - asset: assets/fonts/InstrumentSans-Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/thryve_v2_cropped.png"
  adaptive_icon_foreground: "assets/images/thryve_v2.png"
  adaptive_icon_background: "#555555"
